<?php

/**
 * @file
 * Contains webcam_field.module.
 */

#use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
/**
function webcam_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webcam_field module.
    case 'help.page.webcam_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Webcam field') . '</p>';
      return $output;

    default:
  }
}
 */
